services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/code
    ports:
      - 8081:8081
    environment:
      - AVSG_FRONTENDURL=http://frontend:8082
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend:/code
      - /code/node_modules
